#! ../rtlua/lua
package.loadlib('../rtlua/build/rtlua.so', '*')
local rt = require("rtlua").create_state {}
compiler = require 'dylib-lua'
dylib    = require 'dylib'

function create_loader_header(name, source)
    local header = "#include <dlfcn.h>\n\n"
    local functions = {}
    -- FIXME: this won't work on function names split onto multiple lines
    for line in source:gmatch("[^\n]+") do
        local func_type, func_name, func_args =
            line:match("^([a-zA-Z_][a-zA-Z_* ]*) ([a-zA-Z_ ]*)(%(.*%))")
        if func_type and func_name and func_args then
            table.insert(functions,
                { name=func_name
                , type=func_type
                , args=func_args
                })
        end
    end
    for _,func in ipairs(functions) do
        header = header .. func.type .. "(*" .. func.name .. ")" .. func.args .. ";\n"
    end
    header = header .. "\n"
    header = header .. "void " .. name .. "_Loader(void* Handle) {\n"
    for _,func in ipairs(functions) do
        header = header .. "    " .. func.name .. ' = dlsym(Handle, "' .. func.name .. '");\n'
    end
    header = header .. "}\n"
    return header
end

local woof_lib_source = [[
#include <stdio.h>

void Woof() {
    printf("Woof!!\n");
}

void Bark() {
    printf("Bark!!\n");
}

]]

-- Generate a dynamic loader for woof_lib
local woof_lib_loader = create_loader_header("Woof", woof_lib_source)

---[==[

local woof_lib_handle = dylib.open(compile_source(woof_lib_source))


local double_woof_source = [[
#include <stdio.h>

int DoubleWoof(int NumberOfWoofs) {
    printf("I'm gonna woof %i times!!\n", NumberOfWoofs);
    Woof();
    Woof();
    Bark();
    return 456;
}

]]

-- Generate a Realtalk interface for DoubleWoof
-- (this should be autogenerated)
local double_woof_interface = [[
#include "lua.h"
#include "realtalk.h"
#include "rtlua.h"

rt_ref DoubleWoof_RT(rt_state* RT, rt_ref Arg) {
    int ArgNum = rt_ref_to_number(RT, Arg);
    int Result = DoubleWoof(ArgNum);
    return rt_ref_from_number(RT, Result);
}

]]

-- DoubleWoof depends on WoofLib, so include its loader/header.
double_woof_source = woof_lib_loader .. double_woof_source .. double_woof_interface

local double_woof_handle = dylib.open(compile_source(double_woof_source))

-- Load the functions from Woof into DoubleWoof's namespace
dylib.call_loader(double_woof_handle, "Woof_Loader", woof_lib_handle)

-- Finally, call a function that uses Realtalk as its FFI.
local result = dylib.call_rt(double_woof_handle, "DoubleWoof_RT", rt.value(123))
print(string.format("Double Woof musta woofed like %i times!", result))

---]==]

